runtime: python39

handlers:

  - url: /
    static_files: public/html/index.html
    upload: public/html/index.html

  - url: /favicon\.ico
    static_files: favicon.ico
    upload: favicon\.ico

  - url: /static
    static_dir: public

  - url: /*.html
    static_dir: public/html

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
